### ISSUE TITLE
Missing some resize handles

### ISSUE THREAD

**Issue by mshaddock** [LinxGem33/OSX-Arc-White#19]
First, let me say that this is a great theme; it is very slick.  However, on Mint 18.1 with Mate, I only see resize handles at the top of the window.  There aren't any at the bottom or the sides, so you have to move the window around to resize it.  I realize that this does mimic OSX, but I was wondering if either this was a bug in Mate, or this is deliberate, and if it is deliberate, are there any plans to add them.  Thanks!

**Comment by LinxGem33** [comment]
@mshaddock 
appreciate the feed back, as the theme is based on arc it also inherits semi border less frames which is why you cant grab the corners or the sides there are two possible workarounds in MATE one relatively easy and the other a bit more advanced .


1. use  > ALT & right click < on any area of the window and choose resize.

**or**

2. you can add a slight border to the `metacity-theme-2.xml` the code to look for and change is below highlighted by `>>>` you just need to change the 0's to 1 

```xml
<!-- geometries -->

<frame_geometry name="normal" title_scale="medium" rounded_top_left="1" rounded_top_right="1">
>>>	<distance name="left_width" value="0" />
>>>	<distance name="right_width" value="0" />
>>>	<distance name="bottom_height" value="0" />
	<distance name="left_titlebar_edge" value="5"/>
	<distance name="right_titlebar_edge" value="5"/>
	<distance name="title_vertical_pad" value="6"/>
	<border name="title_border" left="10" right="10" top="3" bottom="3"/>
	<border name="button_border" left="0" right="0" top="0" bottom="0"/>
  <distance name="button_width" value="22"/>
  <distance name="button_height" value="16"/>
</frame_geometry>

<frame_geometry name="normal_unfocused" title_scale="medium" rounded_top_left="1" rounded_top_right="1" parent="normal">
</frame_geometry>

<frame_geometry name="max" title_scale="medium" parent="normal" rounded_top_left="false" rounded_top_right="false">
	<distance name="left_width" value="0" />
	<distance name="right_width" value="0" />
	<distance name="left_titlebar_edge" value="0"/>
	<distance name="right_titlebar_edge" value="0"/>
<distance name="title_vertical_pad" value="2"/>
```
although I don’t suggest changing the code as this could introduce system instability  if you don’t know what your doing, however this will allow you to resize from the sides or bottom

kind regards

**Comment by martinlindhe** [comment]
Hello @LinxGem33 
I have the same issue as @mshaddock here.

The thing is, with current macOS, you can resize windows by dragging in all borders, so the simulated behaviour in this theme is no longer accurate.

However, applying the changes suggested had no effect for me (using XFCE4)

Here's what I did

```
diff --git a/metacity-1/metacity-theme-2.xml b/metacity-1/metacity-theme-2.xml
index a0e23e5..5c5942c 100755
--- a/metacity-1/metacity-theme-2.xml
+++ b/metacity-1/metacity-theme-2.xml
@@ -22,9 +22,9 @@
 <!-- geometries -->
 <frame_geometry name="normal" title_scale="medium" rounded_top_left="1" rounded_top_right="1">
-       <distance name="left_width" value="0" />
-       <distance name="right_width" value="0" />
-       <distance name="bottom_height" value="0" />
+       <distance name="left_width" value="1" />
+       <distance name="right_width" value="1" />
+       <distance name="bottom_height" value="1" />
        <distance name="left_titlebar_edge" value="5"/>
        <distance name="right_titlebar_edge" value="5"/>
        <distance name="title_vertical_pad" value="6"/>
```

ps, sorry for reusing an old bug report but since it is the same issue, I thought it made sense

**Comment by martinlindhe** [comment]
Interestingly enough, it seems the resize grips are available in OSX-Arc-Darker.

I am currently dissecting differences between the two themes

**Comment by martinlindhe** [comment]
Found the issue.

The following files is missing from xfwm4 folder:

bottom-active.xpm, bottom-inactive.xpm, left-active.xpm, left-inactive.xpm, right-active.xpm, right-inactive.xpm

by copying them from OSX-Arc-Darker, it sort of works.

However, bottom-left and bottom-right grabber icons are still lacking.

**Comment by martinlindhe** [comment]
I now realize the issue I had was xfce-specific and doesn't apply to this issue. Sorry again for spamming here.

Anyhow, I've addressed the xfce-specific resize issue with the following patches:

https://github.com/LinxGem33/OSX-Arc-White/pull/37
https://github.com/LinxGem33/OSX-Arc-Darker/pull/13
https://github.com/LinxGem33/OSX-Arc-Shadow/pull/12
