### ISSUE TITLE
Gnome-Global-AppMenu Menu Items are Not Visible

### ISSUE THREAD

**Issue by flourishdna** [LinxGem33/OSX-Arc-White#24]
When I enable OSX-Arc-White as a shell theme the Gnome-Global-AppMenu extension items are not visible as the text and the background color is both white. I have attached a screenshot of the same below.

I had reported it at https://github.com/lestcape/Gnome-Global-AppMenu/issues/32 but it seems this needs to be fixed withing the theme, not the Gnome-Global-AppMenu extension.

![selection_004](https://cloud.githubusercontent.com/assets/8165585/26460497/7189edaa-4197-11e7-92aa-7ba7949051bc.png)

**Comment by LinxGem33** [comment]
@flourishdna 

appreciate the feed back, as this is a new feature ill have to look in to the issue in the meantime could you give me a bit more information regarding your 0S version desktop etc.

kind regards

**Comment by lestcape** [comment]
I'm happy to help if is required.

**Comment by LinxGem33** [comment]
@lestcape 

i think ill be able to fix this issue with the theme i suspect its a gnome shell 3.24 issue, 

but looking at your profile i see you have some experience with extensions and i currently need more contributors on my other project Arc menu which is building quite a lot of interest if your interested in being a part of this project please let me know and ill add you as a member of the development team.

kind regards

**Comment by lestcape** [comment]
@LinxGem33 thanks, i really have not time to be part of your project for now, but i can help a little. So, I will subscribe to the notifications to see the issues of your menu, but i can not promised anything.

You are welcome to contribute in all my projects all people are welcome.
 
I'm trying to migrate all my owns projects from cinnamon to gnome shell.

Also i want to migrate all cinnamon if i can: https://github.com/lestcape/Classic-Gnome. That included the cinnamon-settings where i have a lot of problems, because cinnamon settings was wrote in python+gtk while i migrate all to gjs+gtk and there are some opaque objects in the gnome introspection libraries  https://github.com/GNOME/libgnome-volume-control from gjs, that I can not get in gjs, but they are available from the python side (so that stooped me to continue). I think this is an issue/limitation of the gnome introspection library and the solution is change the audio library it self. Also the fact that there are not way to parse an xml with a native library in gnome shell it's a big limitation to me. I hope they release this https://github.com/GNOME/gxml soon.

Regards.

**Comment by LinxGem33** [comment]
@lestcape 

thanks, regarding your issue with python+gtk I'm very much learning js gnome shell eco system myself(maybe 3 months playing with it?). I'm more of a css guy but I'm getting familiar with GLib stuff because of PyGObject so I think that helps. I also one of the development team pointed me to this link https://lazka.github.io/pgi-docs/ to try to translate it to Gjs because there aren't really any good Gjs docs maybe this might help you regarding your project ill take a look at it as soon as i get a bit more time and see if i can help out in any way.

kind regards

**Comment by Elbullazul** [comment]
@LinxGem33 maybe try this class?

> .not-ornament

**Comment by lestcape** [comment]
The .not-ornament was added because the menu items of the global menu are not at same of the gnome shell menu items. My ornaments are real pictures while gnome shell use special characters. The pictures in my case are to the right while in the gnome shell the ornament are to the left of the items. So, the .not-ornament are only to compensate the gnome shell ornament space without need to add a real actor.

**Comment by Elbullazul** [comment]
@lestcape so what is the class for the menu item in top bar? I have the same issue for my mac theme and I'm wondering which class I need to include

**Comment by flourishdna** [comment]
@LinxGem33 Ubuntu 17.04 with Gnome

**Comment by lestcape** [comment]
In theory, the item in the panel have this class:
popup-menu-item
popup-submenu-menu-item
candidate-index

The application name actor:
    gradient-label-menu-item
    The drawing area:
    chat-meta-message

**Comment by lestcape** [comment]
candidate-index and chat-meta-message are selected because for the gnome shell default theme they have the properties that i need, but of course they are not really related, just they are there for convenience on the default theme.

**Comment by lestcape** [comment]
I re-factor the styles classes a lite to be more easy, used it, now just see this file, it have all that it's needed, related with panel items:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/stylesheet.css

**Comment by LinxGem33** [comment]
@lestcape 
post a screen shot with the the applied style sheet as i haven’t got a VM running,  

```css
.popup-menu-item.applet-box {
padding: 0 0.5em 0 0;`

that’s good as it scales across themes

**Comment by lestcape** [comment]
@LinxGem33 I will merged your style... Thanks.

**Comment by lestcape** [comment]
What you mean with "also hows the spacing on the shell panel ?" Space of item in the panel are set by popup-menu-item.applet-box

There are a better way?

**Comment by LinxGem33** [comment]
@flourishdna 

please test the latest release and let me know if the issue still persists.

kind regards
